name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  update-graphql-schema:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: GPG action import
      #   uses: crazy-max/ghaction-import-gpg@v5
      #   with:
      #     gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      #     passphrase: ${{ secrets.GPG_PASSPHRASE }}
      #     git_user_signingkey: true
      #     git_commit_gpgsign: true

      # - name: Generate GraphQL Schema from Resolvers
      #   run: npx --yes generate:graqphql:schema
      - name: mock graphql schema change
        run: touch report.gql

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: Auto updating grapqhql schema."
          file_pattern: "*.gql"

      - uses: kamilkisiela/graphql-inspector@master
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        with:
          schema: "graphql:report.gql"
          annotations: true
