---
name: Commit on Pull Request Test

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  update-graphql-schema:
    runs-on: ubuntu-latest

    permissions:
      write-all
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      # contents: write
      # actions: read
      # security-events: write

    steps:
      - uses: actions/checkout@v4

      # - name: mock gql change in file
      #   run: date +%s > report.gql

      # - uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: "chore: Auto updating file"
      #     file_pattern: "*.gql"

      - uses: kamilkisiela/graphql-inspector@master
        with:
          schema: "report.gql"
